### ISSUE TITLE
Application Error on form submission

### ISSUE THREAD

**Issue by WhoIsJack** [Research-Support-Network/research-support-network.github.io#13]
I get the following error when filling the form with the example entries listed below and clicking submit.

> **Application error**
> An error occurred in the application and your page could not be served.
> If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). 
> You can do this from the Heroku CLI with the command
> `heroku logs --tail`

List entries: 

- Name: `Jonas Hartmann`
- Affiliation: `University College London (UCL)`
- Country: `United Kingdom (UK)`
- E-mail: `jonas.hartmann@ucl.ac.uk`
- Website: left empty
- Expertise: `Test`

I'm using Firefox.

**Comment by unode** [comment]
Seems like submitting null data can crash the form processing engine at which point it no longer accepts input.
When this happens we need to manually restart the engine or wait for it to idle and restart normally.

It looks like we may be missing some extra validation somewhere or we hit a bug in [staticman](https://staticman.net/).

The logs show:
```
2022-03-11T18:04:43.443763+00:00 app[web.1]: Staticman API running on port 14435
2022-03-11T18:04:43.608726+00:00 heroku[web.1]: State changed from starting to up
2022-03-11T18:04:45.049719+00:00 heroku[router]: at=info method=POST path="/v1/webhook" host=research-support-network.herokuapp.com request_id=22bcad09-bea9-400f-95d3-705207f0065e fwd="140.82.115.109" dyno=web.1 connect=0ms service=137ms status=200 bytes=223 protocol=https
2022-03-11T18:04:46.046106+00:00 app[web.1]: TypeError: null is not a string
2022-03-11T18:04:46.046132+00:00 app[web.1]: at assertString (/app/lib/TypeUtils.js:5:11)
2022-03-11T18:04:46.046133+00:00 app[web.1]: at new Review (/app/lib/models/Review.js:15:5)
2022-03-11T18:04:46.046133+00:00 app[web.1]: at /app/lib/GitHub.js:171:9
2022-03-11T18:04:46.046134+00:00 app[web.1]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-03-11T18:04:46.046134+00:00 app[web.1]: at async Function.module.exports (/app/controllers/handlePR.js:23:18)
2022-03-11T18:04:46.047945+00:00 app[web.1]: node:internal/process/promises:279
2022-03-11T18:04:46.047946+00:00 app[web.1]: triggerUncaughtException(err, true /* fromPromise */);
2022-03-11T18:04:46.047947+00:00 app[web.1]: ^
2022-03-11T18:04:46.047947+00:00 app[web.1]: 
2022-03-11T18:04:46.047948+00:00 app[web.1]: TypeError: null is not a string
2022-03-11T18:04:46.047949+00:00 app[web.1]: at assertString (/app/lib/TypeUtils.js:5:11)
2022-03-11T18:04:46.047949+00:00 app[web.1]: at new Review (/app/lib/models/Review.js:15:5)
2022-03-11T18:04:46.047949+00:00 app[web.1]: at /app/lib/GitHub.js:171:9
2022-03-11T18:04:46.047949+00:00 app[web.1]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-03-11T18:04:46.047950+00:00 app[web.1]: at async Function.module.exports (/app/controllers/handlePR.js:23:18)
2022-03-11T18:04:46.047953+00:00 app[web.1]: 
2022-03-11T18:04:46.047954+00:00 app[web.1]: Node.js v17.6.0
2022-03-11T18:04:46.245311+00:00 heroku[web.1]: Process exited with status 1
2022-03-11T18:04:46.527357+00:00 heroku[web.1]: State changed from up to crashed
2022-03-11T18:08:56.077816+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/v3/entry/github/Research-Support-Network/research-support-network.github.io/main/member-submission" host=research-support-network.herokuapp.com request_id=48321043-5365-4640-8869-214887f30e60 fwd="128.40.51.150" dyno= connect= service= status=503 bytes= protocol=https
```
Once the app enters crashed state it doesn't seem to recover from it unless restarted.

**Comment by WhoIsJack** [comment]
Interesting... hope there aren't too many other things that crash the engine when submitted.

Maybe @tobyhodges has some prior experience with this?

**Comment by unode** [comment]
If anyone manages to crash the engine again, could you keep track of the values you submitted and add them to this thread?

**Comment by unode** [comment]
Actually, I just saw the engine crash again so, those values :smile:

**Comment by Lisanna** [comment]
The email field validation expects an "@", which is not there in case of email obscuration as suggested by the form itself (substituted by [at]). I suggest to remove the email validation.

**Comment by WhoIsJack** [comment]
Oh dear... 

I added the `required` flag to all fields except "Website" and tested a few options of omitting various fields. It seemed to work as intended in terms of preventing submission when some fields were left empty, but when I finally hit "Submit" with everything except the website filled in I got the Application Error again...

Could you please check if I did something wrong?

Also, I wonder if it would be possible to run some sort of cron job that restarts the service automatically when it goes down?

Also also, is it possible to redirect to a "Something has gone wrong - please try again later" landing page instead of "Application Error"?

**Comment by unode** [comment]
Logs show only a repeat of the same message as above. I'm still not sure what triggers it.
The traceback implies that a `null` is generated/passed instead of a string (or empty string).

Regarding cron restart, unfortunately this isn't possible. There is however an automatic shutdown after a period of idleness. If a request is received it will then re-launch. I believe the idle time is 1 hour.

As for redirecting to a different page, it may be possible but I didn't find any docs on how to do it.

**Comment by WhoIsJack** [comment]
Interesting, thanks!

The redirection in case of failure isn't that important, especially if we can reduce the frequency of said failures.

I'm not sure where that `null` is coming from; my understanding is that the default value for empty fields that gets submitted is an empty string.

I have an idea that I will test (after/alongside testing the new landing page I've added).

**Comment by WhoIsJack** [comment]
Hrm... the new landing page works, but I couldn't reproduce the engine crash.

**Comment by WhoIsJack** [comment]
Ok... some thoughts, maybe on the right track, maybe not:

- I had a hunch that it's connected to me denying (closing) staticman pull requests, but couldn't reproduce the crash by doing so
- It then caught my eye that the logs talk about a `webhook` and according to [the staticman docs](https://staticman.net/docs/webhooks), one use of webhooks is to check for PR merging/closing so that the bot can auto-delete the new branch
- We currently don't have any webhooks in place ([as far as I can see](https://github.com/Research-Support-Network/research-support-network.github.io/settings/hooks)), so perhaps it isn't form submission that causes the crash, but rather an attempt by staticman to do something webhook/related. The `null` could reflect the absence of a webhook.
- That said, the bot seems to auto-delete branches just fine... but maybe there are edge cases or something where the absence of a webhook causes staticman to crash when the bot deletes a branch (or something like that).

Not sure how to further investigate this. Guess we can try setting up a webhook? Hard to test if the error can't be reliably induced, though...

**Comment by WhoIsJack** [comment]
Looking at the digging I've done above, do you see anything we can do at this time to reproduce/fix this issue, @unode?

Otherwise, I'd say we'll ask all the list's contributors to sign up as a test, which will hopefully tell us whether we're ready to go ahead and open the list.

**Comment by unode** [comment]
The webhook URL seems to be internal to staticman itself.
Below, submitting a request after a long period of time that made the heroku engine idle out.

```
2022-03-22T12:53:55.542212+00:00 heroku[web.1]: Unidling
2022-03-22T12:53:55.633048+00:00 heroku[web.1]: State changed from down to starting
2022-03-22T12:53:59.676525+00:00 heroku[web.1]: Starting process with command `npm start`
2022-03-22T12:54:01.882394+00:00 heroku[web.1]: State changed from starting to up
2022-03-22T12:54:00.997642+00:00 app[web.1]: 
2022-03-22T12:54:00.997655+00:00 app[web.1]: > staticman@3.0.0 prestart
2022-03-22T12:54:00.997656+00:00 app[web.1]: > if [ ! -d node_modules ]; then npm install; fi
2022-03-22T12:54:00.997656+00:00 app[web.1]: 
2022-03-22T12:54:01.003761+00:00 app[web.1]: 
2022-03-22T12:54:01.003763+00:00 app[web.1]: > staticman@3.0.0 start
2022-03-22T12:54:01.003774+00:00 app[web.1]: > node index.js
2022-03-22T12:54:01.003774+00:00 app[web.1]: 
2022-03-22T12:54:01.754761+00:00 app[web.1]: Staticman API running on port 7954
2022-03-22T12:54:03.695475+00:00 heroku[router]: at=info method=POST path="/v3/entry/github/Research-Support-Network/research-support-network.github.io/main/member-submission" host=research-support-network.herokuapp.com request_id=221ec9a4-02be-4091-b936-1df3b075481c fwd="176.199.210.93" dyno=web.1 connect=0ms service=907ms status=500 bytes=488 protocol=https
2022-03-22T12:54:48.412638+00:00 heroku[router]: at=info method=POST path="/v3/entry/github/Research-Support-Network/research-support-network.github.io/main/member-submission" host=research-support-network.herokuapp.com request_id=31920e46-d6a9-49b1-aa69-ba62d305c2ec fwd="176.199.210.93" dyno=web.1 connect=0ms service=3189ms status=302 bytes=513 protocol=https
2022-03-22T12:54:48.794286+00:00 heroku[router]: at=info method=POST path="/v1/webhook" host=research-support-network.herokuapp.com request_id=42de1a85-f5d1-4dee-aada-e96f8b09a4bb fwd="140.82.115.117" dyno=web.1 connect=0ms service=91ms status=200 bytes=223 protocol=https
```

Above, the first request didn't do a webhook call because the `expertise` field was left empty.
The second went through after adding some text to expertise.

Will also make the form field required to avoid this validation error.

**Comment by WhoIsJack** [comment]
Ok, thanks for looking into this!

Yes, let's have the contributors do a little adversarial test tomorrow.

I'll make a Google form and an alternative sign-up page saying "technical difficulties - please use Google form" in a branch, so we can just swap the deployment to this branch if anything goes wrong during the official launchand the sign-up will immediately be switched to the form.

**Comment by WhoIsJack** [comment]
There's now a branch called [emergency_form_tech_issues](https://github.com/Research-Support-Network/research-support-network.github.io/tree/emergency_form_tech_issues) in which the submission form is replaced by a "technical issues" message with a link to a new [Google form](https://forms.gle/PjBBBAUH6yt2HVTX8) that mimics the sign-up form itself.

Switching to deploying this branch is a matter of seconds (via `Settings > Pages`)

So if we run into any major problems during/after launch, this can work as a backup. If the response volume is large, it shouldn't be hard to write something that automatically parses the csv file Google gives us and creates the corresponding data files. For just a few entries we can simply manually crank them through the webform once it's back up.

**Comment by tobyhodges** [comment]
This is great, thanks both. We will need to merge in the recent changes to `main` (especially the `_data` folder) when switching branches - this will ensure that all the submissions up to that point still show up on the site after the source branch has changed.

**Comment by WhoIsJack** [comment]
Launch testing (issue #51) has shown that the system is quite stable, although we cannot exclude crashes completely.

We have two forms of mitigation in place:
- An easy way for us to check the engine's status and restart it if it has crashed.
- An emergency branch with a replacement Google form that we can deploy in case of sustained errors.

This should be ok; closing here.
